# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout.addWidget(self.tableView)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Withering_btn = QtWidgets.QPushButton(self.frame)
        self.Withering_btn.setObjectName("Withering_btn")
        self.verticalLayout.addWidget(self.Withering_btn)
        self.Decisive_btn = QtWidgets.QPushButton(self.frame)
        self.Decisive_btn.setObjectName("Decisive_btn")
        self.verticalLayout.addWidget(self.Decisive_btn)
        self.other_action_btn = QtWidgets.QPushButton(self.frame)
        self.other_action_btn.setObjectName("other_action_btn")
        self.verticalLayout.addWidget(self.other_action_btn)
        self.add_npc_btn = QtWidgets.QPushButton(self.frame)
        self.add_npc_btn.setObjectName("add_npc_btn")
        self.verticalLayout.addWidget(self.add_npc_btn)
        self.join_battle_btn = QtWidgets.QPushButton(self.frame)
        self.join_battle_btn.setObjectName("join_battle_btn")
        self.verticalLayout.addWidget(self.join_battle_btn)
        self.modify_init_btn = QtWidgets.QPushButton(self.frame)
        self.modify_init_btn.setObjectName("modify_init_btn")
        self.verticalLayout.addWidget(self.modify_init_btn)
        self.remove_from_combat_btn = QtWidgets.QPushButton(self.frame)
        self.remove_from_combat_btn.setObjectName("remove_from_combat_btn")
        self.verticalLayout.addWidget(self.remove_from_combat_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Exalted Initiative"))
        self.Withering_btn.setText(_translate("MainWindow", "Withering Attack"))
        self.Decisive_btn.setText(_translate("MainWindow", "\"Decisive / Gambits\""))
        self.other_action_btn.setText(_translate("MainWindow", "Other Actions"))
        self.add_npc_btn.setText(_translate("MainWindow", "Add NPCs"))
        self.join_battle_btn.setText(_translate("MainWindow", "Join Battle!"))
        self.modify_init_btn.setText(_translate("MainWindow", "Modify Initiative"))
        self.remove_from_combat_btn.setText(_translate("MainWindow", "Remove from Combat"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
