# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Primefactorx01\Documents\Python\ex-3e-init-tracker\lib\attack_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(336, 286)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.attacker_combo = QtWidgets.QComboBox(self.groupBox)
        self.attacker_combo.setObjectName("attacker_combo")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.attacker_combo)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.a_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.a_spinBox.setMinimum(-99)
        self.a_spinBox.setObjectName("a_spinBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.a_spinBox)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.defender_combobox = QtWidgets.QComboBox(self.groupBox_2)
        self.defender_combobox.setObjectName("defender_combobox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.defender_combobox)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.d_spinbox = QtWidgets.QSpinBox(self.groupBox_2)
        self.d_spinbox.setMinimum(-99)
        self.d_spinbox.setObjectName("d_spinbox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.d_spinbox)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.onslaught_lbl = QtWidgets.QLabel(self.groupBox_2)
        self.onslaught_lbl.setObjectName("onslaught_lbl")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.onslaught_lbl)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.damage_spinbox = QtWidgets.QSpinBox(Dialog)
        self.damage_spinbox.setObjectName("damage_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.damage_spinbox)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.rout_spinBox = QtWidgets.QSpinBox(Dialog)
        self.rout_spinBox.setObjectName("rout_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rout_spinBox)
        self.post_soak_damage_exceeds_10_checkBox = QtWidgets.QCheckBox(Dialog)
        self.post_soak_damage_exceeds_10_checkBox.setObjectName("post_soak_damage_exceeds_10_checkBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.post_soak_damage_exceeds_10_checkBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.Hit_Miss = QtWidgets.QGroupBox(Dialog)
        self.Hit_Miss.setTitle("")
        self.Hit_Miss.setObjectName("Hit_Miss")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Hit_Miss)
        self.verticalLayout.setObjectName("verticalLayout")
        self.success_radioButton = QtWidgets.QRadioButton(self.Hit_Miss)
        self.success_radioButton.setObjectName("success_radioButton")
        self.verticalLayout.addWidget(self.success_radioButton)
        self.failed_radioButton = QtWidgets.QRadioButton(self.Hit_Miss)
        self.failed_radioButton.setObjectName("failed_radioButton")
        self.verticalLayout.addWidget(self.failed_radioButton)
        self.verticalLayout_3.addWidget(self.Hit_Miss)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.defender_combobox, self.damage_spinbox)
        Dialog.setTabOrder(self.damage_spinbox, self.attacker_combo)
        Dialog.setTabOrder(self.attacker_combo, self.a_spinBox)
        Dialog.setTabOrder(self.a_spinBox, self.d_spinbox)
        Dialog.setTabOrder(self.d_spinbox, self.rout_spinBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Attacker"))
        self.label_2.setText(_translate("Dialog", "Initiative Modifier"))
        self.label.setText(_translate("Dialog", "Name"))
        self.groupBox_2.setTitle(_translate("Dialog", "Defender"))
        self.label_3.setText(_translate("Dialog", "Name"))
        self.label_4.setText(_translate("Dialog", "Initiative Modifier"))
        self.label_7.setText(_translate("Dialog", "Onslaught Penalty"))
        self.onslaught_lbl.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "Damage"))
        self.label_6.setText(_translate("Dialog", "Rout Checks"))
        self.post_soak_damage_exceeds_10_checkBox.setText(_translate("Dialog", "Post Soak damage exceeds 10"))
        self.success_radioButton.setText(_translate("Dialog", "Successful"))
        self.failed_radioButton.setText(_translate("Dialog", "Failed"))
